### ISSUE TITLE
Cannot Index Existing Profiles

### ISSUE THREAD

**Issue by acupoftee** [acupoftee/Adopt-A-Player-Client#4]
Profile listings should be seen without needing to sign in. When clicking on `Find Players` the console returns the following message:

```
jquery.js:3841 jQuery.Deferred exception: Cannot read property 'length' of null TypeError: Cannot read property 'length' of null
    at Object.limit (http://localhost:7165/public/application.js:411:11)
    at 2 (http://localhost:7165/public/application.js:4449:49)
    at prog (http://localhost:7165/public/application.js:18285:12)
    at execIteration (http://localhost:7165/public/application.js:17713:19)
    at Array.<anonymous> (http://localhost:7165/public/application.js:17723:13)
    at 1 (http://localhost:7165/public/application.js:4434:31)
    at Object.prog [as fn] (http://localhost:7165/public/application.js:18285:12)
    at Object.groupEach (http://localhost:7165/public/application.js:4412:24)
    at Object.main (http://localhost:7165/public/application.js:4499:54)
    at main (http://localhost:7165/public/application.js:18239:32) 
```

The profile listings still exist in the API. Since the curl request works for the user index, a possible source would be in `userEvents.onGetUsers()`

**Comment by acupoftee** [comment]
The issue was in `limit.js`. This helper function triggered my `profile-listings.handlebars` would throw an error if passed in a null string. Here's the updated function:

```js
'use strict'

const limit = (str, length) => {
  if (str) {
    if (str.length <= length) {
      return str
    } else {
      return str.substring(0, length) + '...'
    }
  }
}

module.exports = limit
```
